self.addEventListener('install',e=>{
e.waitUntil(
caches.open('pdf-tools-cache').then(c=>c.addAll([
'./','index.html','manifest.json','icon512.png'
]))
);
self.skipWaiting();
});
self.addEventListener('activate',e=>{e.waitUntil(self.clients.claim());});
self.addEventListener('fetch',e=>{e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request)));});